import Head from "next/head";
import style from "../styles/Layout.module.css";
import NavbarComponent from "./NavbarComponent";
import { Container } from "react-bootstrap";

export default function Layout({ children, title }) {
  return (
    <div>
      <Head>
        <title>Fav-Image {title ? `| ${title}` : ""}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavbarComponent></NavbarComponent>
      <main className={style.container}>
        <Container>{children}</Container>
      </main>
      <footer>
        <Container>Footer</Container>
      </footer>
    </div>
  );
}
